name: "Setup Poetry"
description: "Install Python, Poetry, and dependencies using Caching."

inputs:
  pythonVersion:
    description: "The Python version to use with Poetry"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: actions/setup-python
      with:
        python-version: ${{ inputs.pythonVersion }}

    - name: "Cache dependencies file"
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

    - name: "Load cached Poetry dependencies"
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: poetry-0  # Increment to invalidate cache

    - name: "Install Poetry"
      uses: snok/install-poetry@v1
      with:
        version: 1.1.12
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: "Load cached venv"
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: "Install Project"
      shell: bash
      if: steps.cached-poetry-dependencies.cache-hit != 'true'
      run: poetry install
