
name: "Poetry install"
author: "Nick Cannariato<devrel@birdcar.dev>"
description: "Setup a Python project, install poetry, and cache its dependencies."

inputs:
  pythonVersion:
    required: false
    description: "The specific Python version you'd like to use (defaults to latest version available on Heroku)"
    default: "3.10.3"

runs:
  using: composite
  steps:
  - name: Install poetry
    shell: bash
    run: pipx install poetry
  - uses: actions/setup-python@v3
    with:
      python-version: ${{ inputs.pythonVersion }}
      cache: 'poetry'
  - name: Configure Poetry
    shell: bash
    run: poetry env use $PYTHON_VERSION
    env:
      PYTHON_VERSION: ${{ inputs.pythonVersion }}
