
name: "Create Release"
author: "Nick Cannariato <devrel@birdcar.dev>"
description: "Automatically creates a release from a new Tag on GitHub, including changelog notes"

inputs:
  githubToken:
    required: true
    description: "A GitHub Personal Access Token with the appropriate scopes"
  changelogPath:
    required: false
    description: "Relative path to the Changelog file to parse, defaults to a file named CHANGELOG.md in the root of the repository."
    default: "CHANGELOG.md"
  timezone:
    required: false
    description: An optional Olsen database timezone, defaults to UTC.
    default: 'Etc/UTC'

runs:
  using: "node16"
  main: 'dist/index.js'